#postgres: {}
pmtiles: 
  - /pmtiles/sp-planetiler/sp-osm.pmtiles
  - /pmtiles/sp-protomaps/sp_protomaps.pmtiles 
# mbtiles: {}
# cog: {}
# geojson: {}
fonts:
  paths:
    - /assets/fonts
styles:
  sources:
    openmaptiles-dark-matter-gl-style: /styles/openmaptiles/dark-matter-gl-style/style.json
    openmaptiles-fiord-color-gl-style: /styles/openmaptiles/fiord-color-gl-style/style.json
    openmaptiles-maptiler-3d-gl-style: /styles/openmaptiles/maptiler-3d-gl-style/style.json
    openmaptiles-maptiler-basic-gl-style: /styles/openmaptiles/maptiler-basic-gl-style/style.json
    openmaptiles-maptiler-toner-gl-style: /styles/openmaptiles/maptiler-toner-gl-style/style.json
    openmaptiles-osm-bright-gl-style: /styles/openmaptiles/osm-bright-gl-style/style.json
    openmaptiles-positron-gl-style: /styles/openmaptiles/positron-gl-style/style.json
    protomaps-dark-new: /styles/protomaps/world-darknew.json
sprites:
  sources:
    openmaptiles-common: /assets/svg_icons/openmaptiles/common
    openmaptiles-dark-matter-gl-style: /assets/svg_icons/openmaptiles/dark-matter-gl-style
    openmaptiles-fiord-color-gl-style: /assets/svg_icons/openmaptiles/fiord-color-gl-style
    openmaptiles-maptiler-3d-gl-style: /assets/svg_icons/openmaptiles/maptiler-3d-gl-style
    openmaptiles-maptiler-basic-gl-style: /assets/svg_icons/openmaptiles/maptiler-basic-gl-style
    openmaptiles-maptiler-toner-gl-style: /assets/svg_icons/openmaptiles/maptiler-toner-gl-style
    openmaptiles-osm-bright-gl-style: /assets/svg_icons/openmaptiles/osm-bright-gl-style
    openmaptiles-positron-gl-style: /assets/svg_icons/openmaptiles/positron-gl-style
    app6-pocwargame: /assets/svg_icons/app6-pocwargame

